server {
    listen 80;
    server_name tablo.docker.home;
    return 301 https://tablo.docker.home$request_uri;
}

server {
    listen 443 ssl;
    ssl_certificate     /ssl/certs/star.docker.home.crt;
    ssl_certificate_key /ssl/keys/star.docker.home.key;
    server_name tablo.docker.home;
    location / {
        set $server "tablo-web";
        proxy_pass http://$server:3400;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
